apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-parameters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
    - secretKey: ENV_VAR5
      remoteRef:
        key: krci-cmtr-enc4ehiy-backend-parameters
        property: backend-parameters.ENV_VAR5
    - secretKey: application.secret.properties.from.ps
      remoteRef:
        key: krci-cmtr-enc4ehiy-backend-parameters
        property: backend-parameters.config
        decodingStrategy: Base64
